pool:
  name: myAgentPool

variables:
  azureServiceConnectionId: AzureServiceConnection
  projectRoot: $(System.DefaultWorkingDirectory)
  backendRg: Azuredevops
  backendSa: tfstate3193425499
  backendContainer: tfstate
  backendKey: test.terraform.tfstate
  tfVersion: 1.2.9

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildInfrastructure
    displayName: Build Infrastructure
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: '$(tfVersion)'

    - task: AzureCLI@2
      displayName: Terraform init + validate + apply
      inputs:
        azureSubscription: '$(azureServiceConnectionId)'
        addSpnToEnvironment: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e

          if [ -n "$AZURE_FEDERATED_TOKEN_FILE" ]; then
            export ARM_USE_OIDC=true
            export ARM_OIDC_TOKEN_FILE="$AZURE_FEDERATED_TOKEN_FILE"
            export ARM_CLIENT_ID="$servicePrincipalId"
            export ARM_TENANT_ID="$tenantId"
            export ARM_SUBSCRIPTION_ID="$subscriptionId"
          else
            export ARM_CLIENT_ID="$servicePrincipalId"
            export ARM_CLIENT_SECRET="$servicePrincipalKey"
            export ARM_TENANT_ID="$tenantId"
            export ARM_SUBSCRIPTION_ID="$subscriptionId"
          fi

          cd "$(System.DefaultWorkingDirectory)/terraform/environments/test"

          terraform init \
            -backend-config="resource_group_name=$(backendRg)" \
            -backend-config="storage_account_name=$(backendSa)" \
            -backend-config="container_name=$(backendContainer)" \
            -backend-config="key=$(backendKey)"

          terraform validate
          terraform apply -auto-approve
