pool:
  name: myAgentPool

variables:
  tfVersion: '1.2.9'
  projectRoot: $(System.DefaultWorkingDirectory)
  azureServiceConnectionId: 'AzureServiceConnection'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildInfrastructure
    displayName: Build Infrastructure
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: '$(tfVersion)'

    - task: AzureCLI@2
      displayName: Terraform init + validate + apply (OIDC)
      inputs:
        azureSubscription: '$(azureServiceConnectionId)'
        scriptType: bash
        addSpnToEnvironment: true
        script: |
          export ARM_USE_OIDC=true
          export ARM_CLIENT_ID="$servicePrincipalId"
          export ARM_TENANT_ID="$tenantId"
          export ARM_SUBSCRIPTION_ID="$subscriptionId"

          cd "$(System.DefaultWorkingDirectory)/terraform/environments/test"

          terraform init \
            -backend-config="resource_group_name=Azuredevops" \
            -backend-config="storage_account_name=tfstate3193425499" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=test.terraform.tfstate"

          terraform validate
          terraform apply -auto-approve