pool:
  name: myAgentPool

variables:
  azureServiceConnectionId: AzureServiceConnection
  projectRoot: $(System.DefaultWorkingDirectory)
  backendRg: Azuredevops
  backendSa: tfstate3193425499
  backendContainer: tfstate
  backendKey: test.terraform.tfstate
  tfVersion: 1.2.9

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildInfrastructure
    displayName: Build Infrastructure
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: '$(tfVersion)'

    - task: AzureCLI@2
      displayName: Terraform init + validate + apply (logged in via service connection)
      inputs:
        azureSubscription: '$(azureServiceConnectionId)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd "$(System.DefaultWorkingDirectory)/terraform/environments/test"

          terraform init \
            -backend-config="resource_group_name=$(backendRg)" \
            -backend-config="storage_account_name=$(backendSa)" \
            -backend-config="container_name=$(backendContainer)" \
            -backend-config="key=$(backendKey)"

          terraform validate

          terraform apply -auto-approve