trigger:
- main

pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Archive
    displayName: "Archive FakeRestAPI"
    steps:
    - script: |
        echo "Cleaning up any old FakeRestAPI folder..."
        rm -rf FakeRestAPI
        echo "Creating FakeRestAPI folder..."
        mkdir FakeRestAPI
        echo "Adding a test file to FakeRestAPI..."
        echo "Hello from FakeRestAPI" > FakeRestAPI/index.html
      displayName: "Prepare FakeRestAPI Folder"

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'FakeRestAPI'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/FakeRestAPI.zip'
        replaceExistingArchive: true
      displayName: "Archive FakeRestAPI"

    - publish: '$(Build.ArtifactStagingDirectory)/FakeRestAPI.zip'
      artifact: drop
      displayName: "Publish FakeRestAPI artifact"

- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - deployment: DeployWeb
    displayName: "Deploy to Linux VM"
    environment: 
      name: "linux-test-vm"
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying FakeRestAPI to /var/www/html..."
              sudo apt-get update -y
              sudo apt-get install unzip -y
              unzip $(Pipeline.Workspace)/drop/FakeRestAPI.zip -d /tmp/FakeRestAPI
              sudo mkdir -p /var/www/html
              sudo cp -r /tmp/FakeRestAPI/* /var/www/html/
              echo "Deployment complete!"
            displayName: "Deploy FakeRestAPI to VM"
